# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('showname', models.CharField(max_length=250)),
                ('showdescription', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('automationID', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('profileID', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
