# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_showpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowsIndexPage',
            new_name='ShowIndexPage',
        ),
    ]
